import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { uncachedSanityClient, writeClient } from '@/lib/sanity';
import { resolveUserReferenceIds } from '@/lib/user-references';

// Get user's bookings
export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth();
    
    if (!userId) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Get tenant slug from header
    const tenantSlug = request.headers.get('x-tenant-slug');
    
    if (!tenantSlug) {
      return NextResponse.json(
        { error: 'Tenant slug is required' },
        { status: 400 }
      );
    }

    // First get tenant and all supported user refs (legacy + current)
    const [tenant, userReferenceIds] = await Promise.all([
      uncachedSanityClient.fetch(
        `*[_type == "tenant" && slug.current == $tenantSlug][0] { _id }`,
        { tenantSlug }
      ),
      resolveUserReferenceIds(userId),
    ]);

    if (!tenant) {
      return NextResponse.json(
        { error: 'Tenant not found' },
        { status: 404 }
      );
    }

    // Get class instances with user's bookings for this specific tenant
    const bookings = await uncachedSanityClient.fetch(
      `*[_type == "classInstance" && count(bookings[student._ref in $userReferenceIds]) > 0 && parentClass->tenant._ref == $tenantId] {
        _id,
        date,
        isCancelled,
        parentClass->{
          title,
          instructor->{name},
          danceStyle,
          location,
          tenant->{
            _id,
            slug
          }
        },
        "userBooking": bookings[student._ref in $userReferenceIds][0]
      } | order(date asc)`,
      { userReferenceIds, tenantId: tenant._id }
    );

    return NextResponse.json({ bookings });
  } catch (error) {
    console.error('Error fetching bookings:', error);
    return NextResponse.json(
      { error: 'Failed to fetch bookings' },
      { status: 500 }
    );
  }
}

// Book a class
export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth();
    
    if (!userId) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { classInstanceId } = await request.json();

    // Get tenant slug from header
    const tenantSlug = request.headers.get('x-tenant-slug');
    
    if (!tenantSlug) {
      return NextResponse.json(
        { error: 'Tenant slug is required' },
        { status: 400 }
      );
    }

    // Get the class instance - it must exist in the database
    const classInstance = await uncachedSanityClient.fetch(
      `*[_type == "classInstance" && _id == $classInstanceId && parentClass->tenant->slug.current == $tenantSlug][0] {
        _id,
        _rev,
        date,
        isCancelled,
        remainingCapacity,
        bookings,
        parentClass->{
          _id,
          capacity,
          title,
          instructor,
          location,
          price,
          level,
          danceStyle,
          tenant,
          isActive
        }
      }`,
      { classInstanceId, tenantSlug }
    );

    if (!classInstance) {
      return NextResponse.json(
        {
          code: 'class_not_found',
          error: 'Class instance not found. Please ensure class instances have been generated by an admin.',
        },
        { status: 404 }
      );
    }

    if (!classInstance.parentClass?.isActive) {
      return NextResponse.json(
        { code: 'class_inactive', error: 'Class is not active' },
        { status: 400 }
      );
    }

    if (classInstance.isCancelled) {
      return NextResponse.json(
        { code: 'class_cancelled', error: 'Class is cancelled' },
        { status: 400 }
      );
    }

    if (classInstance.remainingCapacity <= 0) {
      return NextResponse.json(
        { code: 'class_full', error: 'Class is full' },
        { status: 400 }
      );
    }

    const userReferenceIds = await resolveUserReferenceIds(userId);

    // Check if user already booked this class
    const existingBooking = classInstance.bookings?.find(
      (booking: { student?: { _ref?: string } }) =>
        Boolean(booking.student?._ref && userReferenceIds.includes(booking.student._ref))
    );

    if (existingBooking) {
      return NextResponse.json(
        { code: 'already_booked', error: 'Already booked this class' },
        { status: 400 }
      );
    }

    // Check user's active subscriptions - filter by tenant to prevent cross-school usage
    const tenantId = classInstance.parentClass.tenant?._ref;
    const now = new Date();
    const tenantPassIds = await uncachedSanityClient.fetch<string[]>(
      `*[_type == "pass" && tenant._ref == $tenantId]._id`,
      { tenantId }
    );
    const activeSubscriptions = await uncachedSanityClient.fetch<Array<{ _id: string; type: string; remainingClips?: number }>>(
      `*[_type == "subscription" && user._ref in $userReferenceIds && isActive == true && endDate > $now && (tenant._ref == $tenantId || (!defined(tenant) && ((defined(passId) && passId in $tenantPassIds) || (defined(pass._ref) && pass._ref in $tenantPassIds))))] | order(_createdAt desc)`,
      { userReferenceIds, tenantId, now: now.toISOString(), tenantPassIds }
    );

    if (activeSubscriptions.length === 0) {
      return NextResponse.json(
        { 
          code: 'no_active_pass',
          error: 'No active subscription or clipcard', 
          message: 'You need an active pass or subscription to book classes. Visit the Passes & Subscriptions page to purchase one.',
          redirectUrl: `/${tenantSlug}/subscriptions`
        },
        { status: 400 }
      );
    }

    // Find a valid subscription to use
    let subscriptionToUse: { _id: string; type: string; remainingClips?: number } | null = null;
    let bookingType = '';

    // First try to use monthly pass (unlimited)
    const monthlyPass = activeSubscriptions.find((sub) => sub.type === 'monthly');
    if (monthlyPass) {
      subscriptionToUse = monthlyPass;
      bookingType = 'monthly';
    } else {
      // Try to use any pass with remaining classes (single, multi-pass, clipcard)
      const validPass = activeSubscriptions.find(
        (sub) => ['single', 'multi-pass', 'clipcard'].includes(sub.type) && (sub.remainingClips ?? 0) > 0
      );
      if (validPass) {
        subscriptionToUse = validPass;
        bookingType = validPass.type;
      }
    }

    if (!subscriptionToUse) {
      return NextResponse.json(
        { 
          code: 'no_clips_remaining',
          error: 'No valid subscription or clips remaining', 
          message: 'Your current passes have no remaining classes. Purchase a new pass or subscription to continue booking.',
          redirectUrl: `/${tenantSlug}/subscriptions`
        },
        { status: 400 }
      );
    }

    const studentRef = userReferenceIds.find((ref) => ref !== userId) ?? userId;

    // Create booking
    const newBooking = {
      student: {
        _type: 'reference',
        _ref: studentRef,
      },
      bookingType,
      bookingTime: now.toISOString(),
    };

    // Update class instance with new booking
    const updatedBookings = [...(classInstance.bookings || []), newBooking];
    const newRemainingCapacity = classInstance.remainingCapacity - 1;

    await writeClient
      .patch(classInstanceId)
      .set({
        bookings: updatedBookings,
        remainingCapacity: newRemainingCapacity,
      })
      .commit();

    // If using a pass with limited classes, decrease remaining clips
    if (['single', 'multi-pass', 'clipcard'].includes(bookingType)) {
      await writeClient
        .patch(subscriptionToUse._id)
        .set({
          remainingClips: subscriptionToUse.remainingClips - 1,
        })
        .commit();
    }

    return NextResponse.json({
      success: true,
      code: 'booking_confirmed',
      booking: newBooking,
      remainingCapacity: newRemainingCapacity,
      bookingType,
    });
  } catch (error) {
    console.error('Error booking class:', error);
    return NextResponse.json(
      { code: 'booking_failed', error: 'Failed to book class' },
      { status: 500 }
    );
  }
}
